#!/usr/bin/env ruby

APP_ROOT = File.expand_path("../..", File.realpath(__FILE__))

PATH_CHUNKS = APP_ROOT.split('/')

APP_NAME = PATH_CHUNKS[-2] == 'releases' ? PATH_CHUNKS[-3] : PATH_CHUNKS[-1]

ENV['BUNDLE_GEMFILE'] ||= "#{APP_ROOT}/Gemfile"

require 'bundler/setup'
require 'daemons'

options = {
  :multiple   => false,
  :dir_mode   => :normal,
  :dir        => "#{APP_ROOT}/tmp/pids",
  :log_dir    => "#{APP_ROOT}/log",
  :backtrace  => true
}

Daemons.run_proc("#{APP_NAME}-subscriber", options) do
  Dir.chdir APP_ROOT
  require "#{APP_ROOT}/config/environment"
  Subscriber.new.start
end

