#!/usr/bin/env ruby

require 'optparse'
options = {}
OptionParser.new do |opts|
  opts.on('-e', '--environment=ENVIRONMENT', 'Rails environment') do |env|
    ENV['RAILS_ENV'] = env
  end
  opts.on('-p', '--pid-files-directory=DIRECTORY', "Pid files directory") do |dir|
    options[:pid_files_dir] = dir
  end
  opts.on('-l', '--log-files-directory=DIRECTORY', "Log files directory") do |dir|
    options[:log_files_dir] = dir
  end
end.parse!

dir = File.expand_path('../../',  __FILE__)

dir_chunks = dir.split('/')

project_name = dir_chunks[-1]
project_group = dir_chunks[-2]

daemon_name = [project_group, project_name, 'subscriber'].join('-')

daemon_options = {
  :multiple   => false,
  :dir_mode   => :normal,
  :dir        => options[:pid_files_dir] || "#{dir}/tmp/pids",
  :log_dir    => options[:log_files_dir] || "#{dir}/log",
  :backtrace  => true
}

require 'rubygems'
ENV['BUNDLE_GEMFILE'] ||= "#{dir}/Gemfile"

require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])
require 'daemons'

Daemons.run_proc(daemon_name, daemon_options) do
  if ARGV.include?('--')
    ARGV.slice! 0..ARGV.index('--')
  else
    ARGV.clear
  end

  Dir.chdir dir

  require "#{dir}/config/environment"

  Subscriber.new.start
end

